### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by xiaoyueye** [AgoraIO-Community/cordova-video-chat#1]
您好，我看ios 的demo是不完全吗？可以加您好友请教一下吗？QQ：917234557

**Comment by plutoless** [comment]
理论上补齐sdk libs就可以用了，这边不完全主要是遇到了什么错误呢？

**Comment by xiaoyueye** [comment]
> 理论上补齐sdk libs就可以用了，这边不完全主要是遇到了什么错误呢？

libs 不齐了，项目下载之后没有项目启动的那个文件，方便加个qq吗？向您请教一下

**Comment by plutoless** [comment]
@xiaoyueye  建议用cordova cli先建立一个项目，然后把相关的文件带进去
