### ISSUE TITLE
Short demo

### ISSUE THREAD

**Issue by tusharvikky** [AgoraIO-Community/cordova-video-chat#2]
Hello,

Can we have a short demo on how to setup the package along with how to start integrating on the sample project. The code is a hard to understand its working and flow.

Regards

**Comment by plutoless** [comment]
this is a very old one. what do you need?

**Comment by kpwa** [comment]
iv implemented your work, iv been looking for this solution on agora for a while for ios. How do you terminate a call? have u wrapped that function yet?

**Comment by plutoless** [comment]
@kpwa do you have to use a hybrid solution in your project?

**Comment by kpwa** [comment]
im using your cordova plugin with ionic. I have managed to set it up. I can start calls as per your documentaiton. But i cant find other relevant functions like to end calls.

**Comment by plutoless** [comment]
@kpwa you can use https://github.com/AgoraIO-Community/cordova-video-chat/blob/118c7565258f7dac16b541e56b69a0c5f8fc844c/www/agora.js#L81
btw this repository is out of maintenance and it's pretty out dated. i would suggest you to go with React Native or pure native approach to write your RTC app.

**Comment by kpwa** [comment]
Great thanks for the tip!
